Repository tinacms/tinacms, pull requests merged in 2019-10, with the labels that each got.

#350 fix: fix block menu not showing all items
  packages/tinacms/src/plugins/fields/BlocksFieldPlugin.tsx
Labels: fix

#342 feat(git): implement branch summary API
  packages/@tinacms/api-git/src/router.ts
  packages/@tinacms/git-client/src/git-client.ts
Labels: enhancement

#349 feat(git): implement pushOnCommit option
  packages/@tinacms/api-git/src/commit.ts
  packages/@tinacms/api-git/src/router.ts
  packages/@tinacms/git-client/src/git-client.ts
Labels: enhancement

#351 build: npm run nuke
  package.json
Labels: builds

#358 docs: update ROADMAP
  ROADMAP.md
Labels: documentation

#353 refactor: move `createJestConfig` into the @tinacms/scripts package
  packages/@tinacms/api-git/jest.config.js
  packages/@tinacms/core/jest.config.js
  packages/@tinacms/fields/jest.config.js
  packages/@tinacms/form-builder/jest.config.js
  packages/@tinacms/git-client/jest.config.js
  packages/@tinacms/icons/jest.config.js
  packages/@tinacms/scripts/create.jest.config.js
  packages/@tinacms/scripts/index.js
  packages/@tinacms/scripts/package.json
  packages/@tinacms/styles/jest.config.js
  packages/gatsby-tinacms-remark/jest.config.js
  packages/next-tinacms-git/jest.config.js
  packages/next-tinacms-markdown/jest.config.js
  packages/react-dismissible/jest.config.js
  packages/react-tinacms/jest.config.js
  packages/tinacms/jest.config.js
  template/jest.config.js
Labels: builds

#368 build(danger): check (js|tsx?) files for license
  dangerfile.ts
Labels: builds

#372 chore(linting): Turn off react-hooks/exhaustive-deps
  .eslintrc.json
Labels: builds

#375 usePlugin accepts multiple plugins
  packages/react-tinacms/src/use-plugin.tsx
  packages/react-tinacms/src/with-plugin.tsx
Labels: enhancement

#376 docs: clarified release process description
  README.md
Labels: development, documentation

#378 Blocks item props
  packages/demo-gatsby/src/templates/blog-post.js
  packages/tinacms/src/plugins/fields/BlocksFieldPlugin.tsx
Labels: enhancement

#383 Support Gatsby on Windows #382
  packages/gatsby-tinacms-remark/gatsby-node.js
Labels: fix

#395 Add CreateRemarkPlugin class
  dangerfile.ts
  packages/gatsby-tinacms-remark/src/create-remark-plugin.ts
  packages/gatsby-tinacms-remark/src/index.ts
  packages/gatsby-tinacms-remark/src/remark-creator-plugin.ts
  packages/tinacms/src/plugins/create-content-form-plugin.ts
Labels: enhancement
