Repository tinacms/tinacms, pull requests merged in 2020-08, with the labels that each got.

#1391 Inline text children
  packages/react-tinacms-inline/src/fields/inline-text-field.tsx
  packages/react-tinacms-inline/src/fields/inline-textarea-field.tsx
Labels: inline-editing

#1412 Updates `react-tinacms-editor` docs
  packages/react-tinacms-editor/README.md
Labels: documentation

#1415 gatsby-plugin-tinacms: pass enabled option
  packages/gatsby-plugin-tinacms/gatsby-ssr.tsx
Labels: chore

#1363 chore(ci): test Node LTS active releases
  .github/workflows/master.yml
  README.md
Labels: tests

#1430 Updates `demo-next`
  packages/demo-next/pages/index.js
  packages/demo-next/pages/info.js
Labels: chore

#1432 fix ref forwarding in InlineBlocks
  packages/react-tinacms-inline/README.md
  packages/react-tinacms-inline/src/blocks/inline-field-blocks.tsx
Labels: fix

#1429 fix(react-tinacms-inline): preview src passes form values
  packages/react-tinacms-inline/src/fields/inline-image-field.tsx
Labels: fix
