Repository tinacms/tinacms, pull requests merged in 2020-09, with the labels that each got.

#1440 fix: wysiwym image modal issues
  packages/react-tinacms-editor/src/plugins/Image/Menu/ProsemirrorMenu.tsx
Labels: fix, media, wysiwym

#1488 style(tinacms): media mgr mobile style adjustments
  packages/tinacms/src/components/media/breadcrumb.tsx
  packages/tinacms/src/components/media/media-item.tsx
  packages/tinacms/src/components/media/media-manager.tsx
Labels: media, style

#1500 Make default commit message configurable
  packages/react-tinacms-github/src/github-client/github-client.ts
Labels: enhancement
