Repository tinacms/tinacms, pull requests merged in 2020-07, with the labels that each got.

#1311 chore: updated previews error message
  packages/next-tinacms-github/src/next/preview.ts
Labels: chore

#1286 feat: Adds list field plugin
  packages/@tinacms/fields/src/plugins/ListFieldPlugin.tsx
  packages/@tinacms/fields/src/plugins/index.ts
  packages/@tinacms/fields/src/plugins/wrapFieldWithMeta.tsx
  packages/@tinacms/form-builder/src/fields-builder.tsx
  packages/demo-gatsby/data/author.json
  packages/demo-gatsby/src/components/bio.js
  packages/demo-next/data/info.md
  packages/demo-next/pages/info.js
  packages/tinacms/src/tina-cms.ts
Labels: enhancement

#1321 feat: adds git:commit event to GitFile
  packages/@tinacms/git-client/src/git-client.ts
  packages/@tinacms/git-client/src/git-file.ts
  packages/demo-gatsby/data/author.json
  packages/demo-gatsby/src/components/bio.js
Labels: enhancement

#1364 docs: update README
  README.md
Labels: documentation
