Repository tinacms/tinacms, pull requests merged in 2020-04, with the labels that each got.

#962 fix: not possible to come out of code mark which is at end of line
  packages/react-tinacms-editor/src/state/plugins/Common/index.tsx
Labels: wysiwym

#987 chore: use Tina Styles for the Edit Button
  packages/demo-gatsby/src/components/edit-toggle.js
  packages/demo-gatsby/src/templates/blog-post.js
Labels: demo

#1000 fix: dependend on react-textarea-autosize
  packages/react-tinacms-inline/package.json
Labels: fix

#1002 fix: core editor related code cleanup
  packages/react-tinacms-editor/src/core/context/editorState.tsx
  packages/react-tinacms-editor/src/core/index.tsx
  packages/react-tinacms-editor/src/core/styles/CodeMirror.tsx
  packages/react-tinacms-editor/src/core/styles/ProseMirror.tsx
  packages/react-tinacms-editor/src/core/utils/buildEditor.ts
  packages/react-tinacms-editor/src/core/utils/buildTranslator.ts
  packages/react-tinacms-editor/src/index.ts
  packages/react-tinacms-editor/src/plugins/schema/index.ts
  packages/react-tinacms-editor/src/state/plugins/Menu/FloatingTableMenu/AddColumnMenu.tsx
  packages/react-tinacms-editor/src/state/plugins/Menu/FloatingTableMenu/AddRowMenu.tsx
  packages/react-tinacms-editor/src/state/plugins/Menu/FloatingTableMenu/FloatingTableAddMenu.tsx
  packages/react-tinacms-editor/src/state/plugins/Menu/FloatingTableMenu/FloatingTableColumnMenu.tsx
  packages/react-tinacms-editor/src/state/plugins/Menu/FloatingTableMenu/TableOptionsMenu.tsx
  packages/react-tinacms-editor/src/state/plugins/Menu/FloatingTableMenu/index.tsx
  packages/react-tinacms-editor/src/state/plugins/Menu/FormattingDropdown.tsx
  packages/react-tinacms-editor/src/state/plugins/Menu/Image/FloatingImageMenu.tsx
  packages/react-tinacms-editor/src/state/plugins/Menu/Image/ImageMenu.tsx
  packages/react-tinacms-editor/src/state/plugins/Menu/Menu.tsx
  packages/react-tinacms-editor/src/state/plugins/Menu/historyControl.tsx
  packages/react-tinacms-editor/src/state/plugins/Menu/index.tsx
  packages/react-tinacms-editor/src/state/plugins/Menu/markControl.tsx
  packages/react-tinacms-editor/src/state/plugins/links/FloatingLinkForm.tsx
  packages/react-tinacms-editor/src/state/plugins/links/index.tsx
  packages/react-tinacms-editor/src/useProsemirror.tsx
  packages/react-tinacms-editor/src/useProsemirrorTranslator.ts
  packages/react-tinacms-editor/stories/wysiwyg.stories.tsx
Labels: refactor

#1042 Ui fixes
  packages/@tinacms/react-forms/src/FormView.tsx
  packages/@tinacms/react-sidebar/src/components/Sidebar.tsx
  packages/@tinacms/react-sidebar/src/components/SidebarBody.tsx
  packages/next-tinacms-github/src/github/content/getDecodedData.ts
  packages/next-tinacms-github/src/next/preview.ts
  packages/react-tinacms-inline/src/blocks/add-block-menu.tsx
Labels: fix

#1065 GitHub branching
  packages/@tinacms/fields/src/plugins/wrapFieldWithMeta.tsx
  packages/@tinacms/icons/src/Lock.tsx
  packages/@tinacms/icons/src/index.ts
  packages/@tinacms/react-toolbar/src/components/Toolbar.tsx
  packages/react-tinacms-github/src/github-client/github-client.ts
  packages/react-tinacms-github/src/github-client/index.ts
  packages/react-tinacms-github/src/toolbar-plugins/BranchSwitcherPlugin.tsx
  packages/react-tinacms-github/src/toolbar-plugins/RepoInfoPlugin.tsx
  packages/react-tinacms-github/src/toolbar-plugins/index.tsx
  packages/react-tinacms-github/src/toolbar-plugins/pull-request/PRModal.tsx
  packages/react-tinacms-github/src/toolbar-plugins/useGithubToolbarPlugins.tsx
Labels: enhancement
