Repository tinacms/tinacms, pull requests merged in 2020-02, with the labels that each got.

#721 chore(deps): fix lerna warning on bootstrap
  package-lock.json
  package.json
  packages/@tinacms/api-git/package.json
  packages/@tinacms/core/package.json
  packages/@tinacms/fields/package.json
  packages/@tinacms/form-builder/package.json
  packages/@tinacms/forms/package.json
  packages/@tinacms/git-client/package.json
  packages/@tinacms/icons/package.json
  packages/@tinacms/react-core/package.json
  packages/@tinacms/styles/package.json
  packages/@tinacms/teams/package.json
  packages/demo-cra/package.json
  packages/gatsby-tinacms-json/package.json
  packages/gatsby-tinacms-remark/package.json
  packages/react-dismissible/package.json
  packages/react-tinacms-blocks/package.json
  packages/react-tinacms/package.json
  packages/tinacms/package.json
Labels: chore, dependencies, tests

#720 feat: update image settings
  packages/@tinacms/fields/src/Wysiwyg/node-views/ImageView/index.ts
  packages/@tinacms/fields/src/Wysiwyg/state/index.ts
  packages/@tinacms/fields/src/Wysiwyg/state/plugins/Image/index.ts
  packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/ImageMenu/index.tsx
  packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/Menu.tsx
  packages/@tinacms/fields/src/Wysiwyg/state/plugins/Table/index.ts
  packages/@tinacms/fields/src/Wysiwyg/state/plugins/links/LinkFormController.tsx
  packages/@tinacms/fields/src/Wysiwyg/utils.ts
  packages/@tinacms/fields/stories/wysiwyg.stories.tsx
  packages/demo-gatsby/content/blog/toottoot/index.md
Labels: wysiwym

#740 Improve Table Alignment Icons
  packages/@tinacms/icons/src/AlignCenter.tsx
  packages/@tinacms/icons/src/AlignLeft.tsx
  packages/@tinacms/icons/src/AlignRight.tsx
Labels: wysiwym

#739 fix: lerna warning on react-tinacms-inline package
  packages/react-tinacms-inline/package.json
Labels: builds

#713 Add gatsby mdx plugin
  package-lock.json
  packages/demo-gatsby/content/about.mdx
  packages/demo-gatsby/content/blog/cool-post/index.mdx
  packages/demo-gatsby/content/hello.mdx
  packages/demo-gatsby/gatsby-config.js
  packages/demo-gatsby/package-lock.json
  packages/demo-gatsby/package.json
  packages/demo-gatsby/src/components/test-mdx-form.js
  packages/demo-gatsby/src/pages/about.js
  packages/demo-gatsby/src/pages/hello.js
  packages/gatsby-tinacms-mdx/.gitignore
  packages/gatsby-tinacms-mdx/CHANGELOG.md
  packages/gatsby-tinacms-mdx/README.md
  packages/gatsby-tinacms-mdx/gatsby-node.js
  packages/gatsby-tinacms-mdx/index.ts
  packages/gatsby-tinacms-mdx/jest.config.js
  packages/gatsby-tinacms-mdx/package-lock.json
  packages/gatsby-tinacms-mdx/package.json
  packages/gatsby-tinacms-mdx/src/MdxForm.tsx
  packages/gatsby-tinacms-mdx/src/errors.ts
  packages/gatsby-tinacms-mdx/src/form-actions/delete-action.tsx
  packages/gatsby-tinacms-mdx/src/generate-fields.ts
  packages/gatsby-tinacms-mdx/src/index.ts
  packages/gatsby-tinacms-mdx/src/mdx-creator-plugin.ts
  packages/gatsby-tinacms-mdx/src/mdx-fragment.ts
  packages/gatsby-tinacms-mdx/src/mdx-node.ts
  packages/gatsby-tinacms-mdx/src/mdxFormHoc.tsx
  packages/gatsby-tinacms-mdx/src/to-mdx.ts
  packages/gatsby-tinacms-mdx/src/useMdxForm.tsx
  packages/gatsby-tinacms-mdx/tsconfig.json
Labels: enhancement

#747 Adding support for image links
  packages/@tinacms/fields/src/Wysiwyg/node-views/ImageView/index.ts
  packages/@tinacms/fields/src/Wysiwyg/state/plugins/Image/index.ts
  packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/ImageMenu/index.tsx
  packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/Menu.tsx
  packages/@tinacms/fields/src/Wysiwyg/state/plugins/Menu/markControl.tsx
Labels: wysiwym

#781 fix(tinacms): if single form, FormView no longer renders form list
  packages/tinacms/src/components/FormView.tsx
Labels: fix
