Repository tinacms/tinacms, pull requests merged in 2020-03, with the labels that each got.

#850 Inline toolbar scroll fix.
  packages/@tinacms/fields/src/Wysiwyg/state/index.ts
  packages/@tinacms/fields/src/Wysiwyg/state/plugins/Common/index.tsx
Labels: fix

#834 Refactoring link modal to remove it from prosemirror plugin.
  packages/react-tinacms-editor/package.json
  packages/react-tinacms-editor/src/Translator/MarkdownTranslator/commonmark/__tests__/autolink/node.json
  packages/react-tinacms-editor/src/Translator/MarkdownTranslator/commonmark/__tests__/code-link/node.json
  packages/react-tinacms-editor/src/Translator/MarkdownTranslator/commonmark/__tests__/link-discount-pseudoprotcol/node.json
  packages/react-tinacms-editor/src/Translator/MarkdownTranslator/commonmark/__tests__/reference-are-denormalized/node.json
  packages/react-tinacms-editor/src/Translator/MarkdownTranslator/commonmark/__tests__/table_with_marks/node.json
  packages/react-tinacms-editor/src/Wysiwyg.tsx
  packages/react-tinacms-editor/src/commands/link-commands.test.ts
  packages/react-tinacms-editor/src/commands/link-commands.ts
  packages/react-tinacms-editor/src/plugins/keymap.ts
  packages/react-tinacms-editor/src/plugins/schema/marks/link.ts
  packages/react-tinacms-editor/src/prosemirror-test-utils/index.ts
  packages/react-tinacms-editor/src/state/index.ts
  packages/react-tinacms-editor/src/state/plugins/Common/index.tsx
  packages/react-tinacms-editor/src/state/plugins/Menu/FormattingDropdown.tsx
  packages/react-tinacms-editor/src/state/plugins/Menu/Image/FloatingImageMenu.tsx
  packages/react-tinacms-editor/src/state/plugins/Menu/Menu.tsx
  packages/react-tinacms-editor/src/state/plugins/Menu/MenuComponents.tsx
  packages/react-tinacms-editor/src/state/plugins/Menu/blockControl.tsx
  packages/react-tinacms-editor/src/state/plugins/Menu/historyControl.tsx
  packages/react-tinacms-editor/src/state/plugins/Menu/markControl.tsx
  packages/react-tinacms-editor/src/state/plugins/inline-menu/Menu.tsx
  packages/react-tinacms-editor/src/state/plugins/links/FloatingLinkForm.tsx
  packages/react-tinacms-editor/src/state/plugins/links/LinkForm.tsx
  packages/react-tinacms-editor/src/state/plugins/links/LinkView.ts
  packages/react-tinacms-editor/src/state/plugins/links/index.tsx
  packages/react-tinacms-editor/src/useProsemirror.tsx
  packages/react-tinacms-editor/src/utils.ts
Labels: wysiwym

#882 Add webpack helper package
  README.md
  packages/@tinacms/webpack-helpers/README.md
  packages/@tinacms/webpack-helpers/index.js
  packages/@tinacms/webpack-helpers/package.json
Labels: contributing

#903 fix: use TinaProvider instead of Tina
  packages/demo-gatsby/gatsby-browser.js
  packages/gatsby-plugin-tinacms/gatsby-browser.tsx
  packages/gatsby-plugin-tinacms/gatsby-ssr.tsx
Labels: fix

#915 feat: image drag drop support in wysiwym
  packages/demo-gatsby/content/blog/toottoot/index.md
  packages/demo-gatsby/src/templates/blog-post.js
  packages/demo-gatsby/static/images/.gitkeep
  packages/demo-gatsby/static/king.png
  packages/react-tinacms-editor/src/Wysiwyg.tsx
  packages/react-tinacms-editor/src/commands/image-commands.ts
  packages/react-tinacms-editor/src/state/index.ts
  packages/react-tinacms-editor/src/state/plugins/Image/index.ts
  packages/react-tinacms-editor/src/state/plugins/Menu/Image/ImageMenu.tsx
  packages/react-tinacms-editor/src/state/plugins/Menu/Menu.tsx
  packages/react-tinacms-editor/src/state/plugins/Menu/index.tsx
  packages/react-tinacms-editor/src/types.ts
  packages/react-tinacms-editor/src/useProsemirror.tsx
  packages/react-tinacms-editor/stories/wysiwyg.stories.tsx
Labels: wysiwym

#942 chore(react-tinacms-inline): adjust add block logic for single block
  packages/react-tinacms-inline/src/blocks/add-block-menu.tsx
Labels: ux
