Repository tinacms/tinacms, pull requests merged in 2020-05, with the labels that each got.

#1099 feat(github-client): optionally accept scope
  packages/react-tinacms-github/src/github-client/authenticate.ts
  packages/react-tinacms-github/src/github-client/github-client.ts
Labels: enhancement

#1111 fix: close image popup and hitting delete button should delete image
  packages/react-tinacms-editor/src/plugins/Image/Popups/Edit.tsx
Labels: ux

#1130 fix: fragment definitions
  packages/gatsby-tinacms-mdx/mdx-fragment.js
  packages/gatsby-tinacms-mdx/package.json
  packages/gatsby-tinacms-mdx/src/index.ts
  packages/gatsby-tinacms-remark/package.json
  packages/gatsby-tinacms-remark/remark-fragment.js
  packages/gatsby-tinacms-remark/src/index.ts
Labels: fix

#1137 feat: support for strike in wysiwym
  packages/@tinacms/icons/src/Strikethrough.tsx
  packages/@tinacms/icons/src/index.ts
  packages/react-tinacms-editor/src/plugins/Common/input-rules/inputRules.ts
  packages/react-tinacms-editor/src/plugins/Inline/Menu/index.tsx
  packages/react-tinacms-editor/src/schema/index.ts
  packages/react-tinacms-editor/src/schema/marks/strike.ts
  packages/react-tinacms-editor/src/translator/MarkdownTranslator/commonmark/tokens.ts
  packages/react-tinacms-editor/src/translator/MarkdownTranslator/from_markdown.ts
Labels: enhancement, wysiwym

#1139 demo-gatsby: fixes create new blog action
  packages/demo-gatsby/src/components/layout.js
Labels: demo

#1152 Feat: Tags Field
  packages/@tinacms/fields/src/plugins/TagsFieldPlugin.tsx
  packages/@tinacms/fields/src/plugins/index.ts
  packages/demo-next/data/index.json
  packages/demo-next/pages/index.js
  packages/tinacms/src/tina-cms.ts
Labels: tina-plugin

#1134 Remove Markdown/Html Editors from Default Plugins
  packages/demo-gatsby/package.json
  packages/demo-gatsby/src/templates/blog-post.js
  packages/react-tinacms-editor/package.json
  packages/react-tinacms-editor/src/index.ts
  packages/react-tinacms-editor/src/tinacms-inline/inline-wysiwyg.tsx
  packages/react-tinacms-editor/src/tinacms-plugins/HtmlFieldPlugin.tsx
  packages/react-tinacms-editor/src/tinacms-plugins/MarkdownFieldPlugin.tsx
  packages/react-tinacms-editor/src/tinacms-plugins/wysiwygStyles.tsx
  packages/react-tinacms-inline/src/index.tsx
  packages/tinacms/package.json
  packages/tinacms/src/index.ts
  packages/tinacms/src/plugins/fields/index.ts
  packages/tinacms/src/plugins/fields/markdown.tsx
  packages/tinacms/src/tina-cms.ts
Labels: perf

#1173 Adds error alert for inline image
  packages/react-tinacms-inline/src/fields/inline-image-field.tsx
Labels: ux

#1176 Refactor: Rename inline fields
  packages/demo-gatsby/src/components/blog-blocks.js
  packages/demo-gatsby/src/templates/blog-post.js
  packages/demo-next/pages/blocks.tsx
  packages/demo-next/pages/blog/[slug].tsx
  packages/demo-next/pages/info.js
  packages/react-tinacms-inline/src/blocks/inline-block-image.tsx
  packages/react-tinacms-inline/src/blocks/inline-block-text.tsx
  packages/react-tinacms-inline/src/blocks/inline-block-textarea.tsx
  packages/react-tinacms-inline/src/blocks/inline-field-blocks.tsx
  packages/react-tinacms-inline/src/fields/inline-image-field.tsx
  packages/react-tinacms-inline/src/fields/inline-text-field.tsx
  packages/react-tinacms-inline/src/fields/inline-textarea-field.tsx
  packages/react-tinacms-inline/src/index.tsx
Labels: inline-editing, refactor

#1150 fix: we weren't handling time formatting in any way
  packages/tinacms/src/plugins/fields/DateFieldPlugin.tsx
  packages/tinacms/src/plugins/fields/dateFormat.test.ts
  packages/tinacms/src/plugins/fields/dateFormat.ts
Labels: fix

#1185 Add note on node version to README
  README.md
Labels: contributing

#1186 (react-tinacms-inline): Consolidates focus ring
  packages/demo-next/pages/info.js
  packages/react-tinacms-inline/src/blocks/inline-block-field-controls.tsx
  packages/react-tinacms-inline/src/inline-group/inline-group-controls.tsx
  packages/react-tinacms-inline/src/styles/focus-ring.tsx
  packages/react-tinacms-inline/src/styles/index.ts
  packages/react-tinacms-inline/src/styles/input-focus-wrapper.tsx
Labels: inline-editing, style
