Repository tinacms/tinacms, pull requests merged in 2020-11, with the labels that each got.

#1580 chore(react-tinacms-editor): adds react-tinacms-inline as peerDep
  packages/react-tinacms-editor/package.json
Labels: dependencies

#1582 chore(deps): React 17
  package-lock.json
  package.json
  yarn.lock
Labels: chore

#1592 style: add css override
  packages/@tinacms/fields/src/components/Input.tsx
  packages/@tinacms/fields/src/components/Select.tsx
  packages/@tinacms/react-modals/src/Modal/ModalHeader.tsx
Labels: style

#1585 Add true/false toggle labels to Toggle plugin
  packages/@tinacms/fields/src/components/Toggle.tsx
Labels: enhancement

#1572 fix(react-tinacms-inline): better control InlineBlocks rerenders
  packages/react-tinacms-inline/src/blocks/inline-field-blocks.tsx
Labels: inline-editing, perf

#1595 Feat(@tinacms/fields): add labels to toggle field
  packages/@tinacms/fields/src/components/Toggle.tsx
  packages/demo-next/pages/nesting.tsx
Labels: enhancement

#1594 Fix(@tinacms/fields): onClear resets the image input
  packages/@tinacms/fields/src/plugins/ImageFieldPlugin.tsx
  packages/demo-gatsby/src/templates/blog-post.js
  packages/demo-next/pages/info.js
Labels: fix

#1606 style: fix font color
  packages/@tinacms/react-toolbar/src/components/DesktopLabel.tsx
  packages/react-tinacms-inline/src/blocks/add-block-menu.tsx
Labels: style

#1607 style: improve z-index
  packages/@tinacms/fields/src/components/ColorPicker/ColorPicker.tsx
  packages/@tinacms/react-modals/src/Modal/ModalOverlay.tsx
  packages/@tinacms/react-sidebar/src/components/Sidebar.tsx
  packages/@tinacms/react-toolbar/src/components/Toolbar.tsx
  packages/@tinacms/styles/src/Styles.tsx
  packages/react-tinacms-inline/src/blocks/add-block-menu.tsx
  packages/react-tinacms-inline/src/styles/focus-ring.tsx
Labels: style

#1608 chore(react-tinacms-inline): Update block container props
  packages/react-tinacms-inline/README.md
  packages/react-tinacms-inline/src/blocks/inline-field-blocks.tsx
Labels: inline-editing

#1615 Pluggable media pagination
  packages/demo-next/pages/_app.js
  packages/demo-next/plugins/CustomPaginator.tsx
  packages/tinacms/src/components/media/index.ts
  packages/tinacms/src/components/media/media-manager.tsx
  packages/tinacms/src/components/media/pagination.tsx
  packages/tinacms/src/index.ts
  packages/tinacms/src/tina-cms.ts
Labels: media

#1619 feat(react-tinacms-inline): InlineGroup field names are relative
  packages/react-tinacms-inline/jest.config.js
  packages/react-tinacms-inline/package.json
  packages/react-tinacms-inline/src/inline-group/inline-group.test.tsx
  packages/react-tinacms-inline/src/inline-group/inline-group.tsx
Labels: inline-editing

#1623 feat: Use custom actions in BlocksControls
  packages/demo-next/pages/nesting.tsx
  packages/react-tinacms-inline/src/blocks/inline-block-field-controls.tsx
Labels: enhancement

#1627 style: fix inline add block z-index bug
  packages/react-tinacms-inline/src/blocks/add-block-menu.tsx
Labels: style

#1622 feat(tinacms): media manager dropzone accepts multiple files for upload
  packages/tinacms/src/components/media/breadcrumb.tsx
  packages/tinacms/src/components/media/media-manager.tsx
Labels: enhancement, media

#1633 fix(@tinacms/fields): input doesn't unset all styles
  packages/@tinacms/fields/src/components/Input.tsx
Labels: Critical/High, fix
