Repository tinacms/tinacms, pull requests merged in 2021-01, with the labels that each got.

#1687 Suggested trick for pushing menu below toolbar
  packages/react-tinacms-editor/README.md
Labels: documentation

#1690 fix(@tinacms/react-sidebar): fixed site elements relative to SiteWrapper
  packages/@tinacms/react-sidebar/src/components/Sidebar.tsx
Labels: fix

#1684 feat(react-tinacms-inline): inline block duplicate action
  packages/@tinacms/icons/src/Duplicate.tsx
  packages/@tinacms/icons/src/index.ts
  packages/react-tinacms-inline/src/blocks/inline-block-field-controls.tsx
  packages/react-tinacms-inline/src/blocks/inline-field-blocks.tsx
Labels: enhancement, ux

#1701 docs: update maintainers
  README.md
Labels: chore

#1714 Revert "fix(@tinacms/react-sidebar): fixed site elements relative to SiteWrapper"
  packages/@tinacms/react-sidebar/src/components/Sidebar.tsx
Labels: fix
