Repository tinacms/tinacms, pull requests merged in 2021-02, with the labels that each got.

#1718 docs: typo
  packages/react-tinacms-date/README.md
Labels: documentation

#1703 Some options for GlobalFormPlugin can't be passed through useFormScreenPlugin
  packages/tinacms/src/react-tinacms/use-form.ts
Labels: enhancement

#1720 docs: Add cleanup function to 'useEffect' example of dynamic imports.
  packages/react-tinacms-editor/README.md
Labels: documentation

#1719 Stop event propagation
  packages/@tinacms/fields/src/components/ColorPicker/ColorPicker.tsx
Labels: fix

#1739 fix: typo in GithubUploadResponse type
  packages/react-tinacms-github/src/github-media-store/index.ts
Labels: fix
