Repository tinacms/tinacms, pull requests merged in 2021-04, with the labels that each got.

#1791 Fix/form portal zindex management
  packages/@tinacms/fields/src/components/ColorPicker/ColorPicker.tsx
  packages/@tinacms/fields/src/plugins/BlocksFieldPlugin.tsx
  packages/@tinacms/fields/src/plugins/GroupFieldPlugin.tsx
  packages/@tinacms/fields/src/plugins/GroupListFieldPlugin.tsx
  packages/@tinacms/react-forms/src/FormPortal.tsx
Labels: fix

#1796 fix: alert container click blocking
  packages/@tinacms/react-alerts/src/Alerts.tsx
Labels: bug, ux

#1795 feat: drag to resize sidebar
  packages/@tinacms/react-sidebar/src/components/ResizeHandle.tsx
  packages/@tinacms/react-sidebar/src/components/Sidebar.tsx
Labels: ux
